### PR TITLE
translate: add filesys plugin

### LINKED ISSUE #104: Adding a Custom Filesystem Plugin
* Markdown文件：[文件地址](https://github.com/xitu/tensorflow/blob/zh-hans/tensorflow/docs_src/extend/add_filesys.md)
  * PR 地址：#151
  ----
  * 翻译时间：5 天
  * 校对时间：1 天
  * 翻译积分：5 分
  * 校对积分：1.5 分
  * [积分有什么用](https://github.com/xitu/gold-miner/wiki)

### PR DESCRIPTION
**Pull request by jasonxia23**
Adding a Custom Filesystem Plugin
resolve #104

### CODE REVIEW

**Comment by GanymedeNil** [comment]
@leviding 校对认领

**Comment by leviding** [comment]
@GanymedeNil ok

**Comment by GanymedeNil** [comment]
@jasonxia23 @leviding

**Comment by wzy816** [comment]
@leviding 校对认领

**Pull request merged**
